name: ubports-installer
title: UBports Installer
adopt-info: ubports-installer
summary: The easy way to install Ubuntu Touch on UBports devices.
description: A friendly cross-platform Installer for Ubuntu Touch. Just connect a supported device to your PC, follow the on-screen instructions and watch this awesome tool do all the rest.
icon: build/icons/icon.png
architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64
license: GPL-3.0

grade: stable
confinement: strict
base: core20

apps:
  ubports-installer:
    command: ./app/ubports-installer --no-sandbox
    plugs:
      - home
      - unity7
      - browser-support
      - network
      - gsettings
      - opengl
      - adb-support
      - raw-usb
      - desktop
      - desktop-legacy
      - wayland
    environment:
      "FONTCONFIG_PATH": "$SNAP/etc/fonts"
      "FONTCONFIG_FILE": "$SNAP/etc/fonts/fonts.conf"
      "XDG_DATA_HOME": "$SNAP/usr/share"
      "LD_LIBRARY_PATH": "$SNAP_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/"

parts:
  ubports-installer:
    plugin: dump
    source: .
    build-packages:
      - npm
      - nodejs
      - libgconf-2-4
    stage-packages:
      - libusb-1.0-0
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - libgtk-3-0
      - libx11-xcb-dev
      - libdrm-common
      - libgbm1
      - libxcb-dri3-0
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `cat $SNAPCRAFT_PROJECT_DIR/package.json | grep version | sed s/'  \"version\": \"'//g | sed s/'\",'//g`
    override-build: |
      echo "Running override-build script"
      echo "https_proxy: " $https_proxy
      echo "http_proxy: " $http_proxy
      echo "updating nodejs" && nvm use stable
      echo "updating npm" && npm install npm@latest -g
      echo "installing dependencies" && npx cross-env ELECTRON_GET_USE_PROXY=true GLOBAL_AGENT_HTTPS_PROXY=$https_proxy npm install
      echo "prerendering" && npm run prerender
      [ `uname -m` == "aarch64" ] && UBPORTS_ARCH=arm64 || UBPORTS_ARCH=x64
      [ `uname -m` == "aarch64" ] && UBPORTS_DISTDIR=linux-arm64-unpacked || UBPORTS_DISTDIR=linux-unpacked
      ELECTRON_GET_USE_PROXY=true
      GLOBAL_AGENT_HTTPS_PROXY=$https_proxy
      ./build.js -o 'linux' -p 'dir' -a $UBPORTS_ARCH -e '{"package": "snap"}'
      mkdir -p $SNAPCRAFT_PART_INSTALL/app
      rm -rf $SNAPCRAFT_PART_INSTALL/app/*
      mv dist/$UBPORTS_DISTDIR/* $SNAPCRAFT_PART_INSTALL/app
    prime:
      - -node_modules
      - -lib/node_modules
      - -**/arm/**
      - -**/arm64/**
      - -**/ia32/**
