name: ubports-installer
version: 0.1.11-beta
summary: ubports-installer
description: UBports Installer, install Ubuntu Touch on your device.
icon: build/icons/icon.png

grade: stable
confinement: strict

apps:
  ubports-installer:
    command: desktop-launch $SNAP/bin/snap-wrapper
    plugs:
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
      - raw-usb

parts:
  ubports-installer:
    plugin: nodejs
    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    after:
      - desktop-glib-only
    build: ./build.js -lb
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/app
      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app
      mv bin/* $SNAPCRAFT_PART_INSTALL/bin
    prime:
      - -node_modules
      - -lib/node_modules
  android-tools:
    source: https://github.com/ubports/android-tools.git
    plugin: make
    build-packages:
      - gir1.2-glib-2.0
      - libglib2.0-dev
      - libselinux-dev
      - libhybris-dev
      - libsystemd-dev
      - libssl-dev
      - python
      - zlib1g-dev
