name: ubports-installer
title: UBports Installer
adopt-info: ubports-installer
summary: The easy way to install Ubuntu Touch on UBports devices.
description: A friendly cross-platform Installer for Ubuntu Touch. Just connect a supported device to your PC, follow the on-screen instructions and watch this awesome tool do all the rest.
icon: build/icons/icon.png
architectures: [amd64]
license: GPL-3.0

grade: stable
confinement: strict
base: core20

apps:
  ubports-installer:
    command: ./app/ubports-installer --no-sandbox
    plugs:
      - home
      - unity7
      - browser-support
      - network
      - gsettings
      - opengl
      - adb-support
      - raw-usb
      - desktop
      - desktop-legacy
      - wayland
    environment:
      "FONTCONFIG_PATH": "$SNAP/etc/fonts"
      "FONTCONFIG_FILE": "$SNAP/etc/fonts/fonts.conf"
      "XDG_DATA_HOME": "$SNAP/usr/share"
      "LD_LIBRARY_PATH": "$SNAP_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/"

parts:
  ubports-installer:
    plugin: dump
    source: .
    build-packages:
      - npm
      - nodejs
      - libgconf-2-4
      - unzip # todo remove
      - wget # todo remove
    stage-packages:
      - libusb-1.0-0
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - libgtk-3-0
      - libx11-xcb-dev
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `cat $SNAPCRAFT_PROJECT_DIR/package.json | grep version | sed s/'  \"version\": \"'//g | sed s/'\",'//g`
    override-build: |
      echo "Running override-build script"
      npm install npm@latest -g
      npx npm install
      cd $SNAPCRAFT_PROJECT_DIR
      rm -rf platform-tools
      mkdir -p platform-tools/linux
      wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip -O platform-tools/adb-fastboot.zip
      unzip platform-tools/adb-fastboot.zip -d platform-tools/linux_tmp
      mv platform-tools/linux_tmp/platform-tools/* platform-tools/linux
      wget https://heimdall.free-droid.com/heimdall-linux.zip -O platform-tools/heimdall.zip
      unzip platform-tools/heimdall.zip -d platform-tools/linux
      ./build.js -o 'linux' -p 'dir' -d
      mkdir -p $SNAPCRAFT_PART_INSTALL/app
      rm -rf $SNAPCRAFT_PART_INSTALL/app/*
      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app
    prime:
      - -node_modules
      - -lib/node_modules
      - -**/arm/**
      - -**/arm64/**
      - -**/ia32/**
