name: ubports-installer
title: UBports Installer
adopt-info: ubports-installer
summary: The easy way to install Ubuntu Touch on UBports devices.
description: A friendly cross-platform Installer for Ubuntu Touch. Just connect a supported device to your PC, follow the on-screen instructions and watch this awesome tool do all the rest.
icon: build/icons/icon.png
architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64
license: GPL-3.0

grade: stable
confinement: strict
base: core20

layout:
  /usr/lib/p7zip:
    symlink: $SNAP/usr/lib/p7zip

apps:
  ubports-installer:
    environment:
      USE_SYSTEM_TOOLS: "true"
      USE_SYSTEM_7ZA: "true"
    command: ./app/ubports-installer --no-sandbox
    extensions:
      - gnome-3-38
    plugs:
      - home
      - browser-support
      - network
      - adb-support
      - raw-usb

parts:
  heimdall:
    # Don't use the cmake plugin as Heimdall doesn't install
    # anything and causes the build step to fail otherwise.
    plugin: nil
    source: https://github.com/Benjamin-Dobell/Heimdall.git
    source-tag: v1.4.2
    build-snaps:
      - cmake
    build-packages:
      - g++
      - zlib1g-dev
      - libusb-1.0-0-dev
    stage-packages:
      - libusb-1.0-0
    override-build: |
      cd $SNAPCRAFT_PART_BUILD
      rm -f ./bin/heimdall

      cmake $SNAPCRAFT_PART_SRC \
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
          -DDISABLE_FRONTEND=ON
      make -j$(nproc --all)

      [ ! -f ./bin/heimdall ] && exit 1

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      rm -f $SNAPCRAFT_PART_INSTALL/usr/bin/heimdall
      cp -a ./bin/heimdall $SNAPCRAFT_PART_INSTALL/usr/bin/
    prime:
      - -usr/share

  android-tools:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_C_COMPILER=/usr/bin/clang-12
      - -DCMAKE_CXX_COMPILER=/usr/bin/clang++-12
      - -DCMAKE_C_FLAGS="-I/snap/protobuf/current/include"
      - -DCMAKE_CXX_FLAGS="-I/snap/protobuf/current/include"
      - -DProtobuf_PROTOC_EXECUTABLE=/opt/ubports-installer-build/bin/protoc
      - -DProtobuf_DIR=/snap/protobuf/current
      - -DProtobuf_USE_STATIC_LIBS=ON
      - -DProtobuf_LIBRARY=/snap/protobuf/current/lib/libprotobuf.a
      - -DProtobuf_INCLUDE_DIR=/snap/protobuf/current/include
      - -DANDROID_TOOLS_USE_BUNDLED_FMT=ON
      - -DANDROID_TOOLS_USE_BUNDLED_LIBUSB=ON
      - -DANDROID_TOOLS_LIBUSB_ENABLE_UDEV=ON
    source: https://github.com/nmeum/android-tools.git
    source-tag: 37.0.0
    build-snaps:
      - cmake
      - protobuf
    build-packages:
      - clang-12
      - libstdc++-10-dev
      - patch
      - dpkg-dev
      - libpcre2-dev
      - googletest
      - libbrotli-dev
      - libzstd-dev
      - liblz4-dev
      - perl
      - libgtest-dev
      - libudev-dev
    stage-packages:
      - libbrotli1
      - libzstd1
      - liblz4-1
    override-pull: |
      snapcraftctl pull
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      # This project applies patches on top of Git and must be reset
      # accordingly in case a previous snapcraft attempt failed.
      git config --global --add safe.directory .
      git submodule update --init --recursive --recommend-shallow
      git submodule foreach 'git config --global --add safe.directory $path'
      find .git/ -type f,d -name rebase-apply -exec rm -rf {} \;

      # Workaround:
      # protoc from 20.04 gets confused by optional proto3 fields
      # protoc from the Snap supports them through an argument,
      # so wrap the invokation and reference in the cmake-parameters.
      # Clean all of this up and replace with apt's protoc once
      # we moved the installer to core24.
      mkdir -p /opt/ubports-installer-build/bin
      echo -e "#!/bin/bash\n/snap/bin/protoc \$@ --experimental_allow_proto3_optional" > /opt/ubports-installer-build/bin/protoc
      chmod 755 /opt/ubports-installer-build/bin/protoc

      snapcraftctl build
    prime:
      - usr/bin/adb
      - usr/bin/fastboot
      - usr/bin/img2simg
      - usr/bin/simg2img
      - usr/bin/make_f2fs
      - usr/bin/mke2fs.android
      - usr/bin/e2fsdroid
      - usr/lib

  ubports-installer:
    after:
      - heimdall
      - android-tools
    plugin: dump
    source: .
    build-snaps:
      - node/18/stable
    build-packages:
      - npm
    stage-packages:
      - libnss3
      - p7zip-full
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `cat $SNAPCRAFT_PROJECT_DIR/package.json | grep version | sed s/'  \"version\": \"'//g | sed s/'\",'//g`
    override-build: |
      echo "Running override-build script"
      http_proxy="${http_proxy:-}"
      https_proxy="${https_proxy:-}"
      echo "https_proxy: " $https_proxy
      echo "http_proxy: " $http_proxy
      echo "installing dependencies" && npx cross-env ELECTRON_GET_USE_PROXY=true GLOBAL_AGENT_HTTPS_PROXY=$https_proxy npm install || sleep 15 && npx cross-env ELECTRON_GET_USE_PROXY=true GLOBAL_AGENT_HTTPS_PROXY=$https_proxy npm install
      echo "rollup" && npm run build
      [ `uname -m` == "aarch64" ] && UBPORTS_ARCH=arm64 || UBPORTS_ARCH=x64
      [ `uname -m` == "aarch64" ] && UBPORTS_DISTDIR=linux-arm64-unpacked || UBPORTS_DISTDIR=linux-unpacked
      ELECTRON_GET_USE_PROXY=true
      GLOBAL_AGENT_HTTPS_PROXY=$https_proxy
      ./build.js -o 'linux' -p 'dir' -a $UBPORTS_ARCH -e '{"package": "snap"}'
      mkdir -p $SNAPCRAFT_PART_INSTALL/app
      rm -rf $SNAPCRAFT_PART_INSTALL/app/*
      mv dist/$UBPORTS_DISTDIR/* $SNAPCRAFT_PART_INSTALL/app
    prime:
      - -node_modules
      - -lib/node_modules
      - -usr/share
      - -**/arm/**
      - -**/arm64/**
      - -**/ia32/**
