name: ubports-installer
version: readfromscript
summary: The easy way to install Ubuntu Touch on UBports devices.
description: A friendly cross-platform Installer for Ubuntu Touch. Just connect a supported device to your PC, follow the on-screen instructions and watch this awesome tool do all the rest.
icon: build/icons/icon.png
architectures: [amd64]

grade: stable
confinement: strict
base: core18

apps:
  ubports-installer:
    command: ./app/ubports-installer
    plugs:
      - home
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
      - adb-support
      - raw-usb
      - desktop
      - desktop-legacy
      - wayland
    environment:
      "FONTCONFIG_PATH": "$SNAP/etc/fonts"
      "FONTCONFIG_FILE": "$SNAP/etc/fonts/fonts.conf"
      "XDG_DATA_HOME": "$SNAP/usr/share"
      "LD_LIBRARY_PATH": "$SNAP_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/"

parts:
  ubports-installer:
    plugin: dump
    source: .
    build-packages:
      - npm
      - nodejs
      - libgconf-2-4
    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `cat package.json | grep version | sed s/'  \"version\": \"'//g | sed s/'\",'//g`
    override-build: |
      echo "Running override-build script"
      npm install
      ./build.js -o 'linux' -p 'dir'
      mkdir -p $SNAPCRAFT_PART_INSTALL/app
      rm -rf $SNAPCRAFT_PART_INSTALL/app/*
      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app
    prime:
      - -node_modules
      - -lib/node_modules
